### ISSUE TITLE
Disable Sound

### ISSUE THREAD

**Issue by Hantersob** [ColdSpirit0/FastCopyLinks#10]
Is there a way to disable the pop.mp3 sound? I tried some ways like editing the .xpi file, but nothing works. 
I really like your extension, but the pop.mp3 sound is ... kind of annoying. 
It would be really nice. 
If there is already a way, please tell me how to do it, I don't get it.

**Comment by ColdSpirit0** [comment]
@Hantersob hi! You can click on addon icon and uncheck "play copy sound".

**Comment by ColdSpirit0** [comment]
@Hantersob please create a new issue if you still cant disable sound that way.
