### ISSUE TITLE
Disable Sound

### ISSUE THREAD

**Issue by Hantersob** [ColdSpirit0/FastCopyLinks#11]
Thanks for your replay, but I still don't know where.

http://0x0.st/HiID.png

The 3 Buttons on the top are just "disable" (not disable the sound) or "report"

**Comment by ColdSpirit0** [comment]
@Hantersob in addons panel click on the addon icon - you will see the window, then click on the checkbox.
![изображение](https://user-images.githubusercontent.com/16982207/225631794-75813589-e659-46af-956d-0a737b5cca54.png)

Icon can be hidden under puzzle icon - you can move it out.

**Comment by Hantersob** [comment]
ahhhh, thanks, it worked
