### ISSUE TITLE
don't working

### ISSUE THREAD

**Issue by ghost** [ColdSpirit0/FastCopyLinks#3]
don't working in FF 67, e10s disabled, don't copy anything

**Comment by ColdSpirit0** [comment]
I installed FF67 and disabled multiprocessor support - everything works fine.
Check if you reloaded the page you are copying from after installing the add-on. Also, the addon does not work on some Mozilla sites.

**Comment by mrochaaa** [comment]
here don't work, maybe something with my profile, bu thanks your attention,
