### ISSUE TITLE
Change the keyboard shortcut for Mac users?

### ISSUE THREAD

**Issue by srikat** [ColdSpirit0/FastCopyLinks#4]
Hi,

Your extension works fine as expected.

I am wondering if you could add an option to change the keyboard shortcut to Cmd + C for Mac users.

Thanks in advance.

**Comment by xanoni** [comment]
I implemented this here: https://github.com/ColdSpirit0/FastCopyLinks/pull/7

**Comment by ColdSpirit0** [comment]
Hi @srikat. Im uploaded @xanoni's changes, it should work on MacOS now. Maybe you need to update it manually first: https://support.mozilla.org/en-US/kb/how-update-add-ons

If it still not work, please create new issue.
